server.error.include-message=always

# ??????????? ? ???? ?????? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tictactoe
# ??? ???????????? (?? ?????????)
spring.datasource.username=postgres
# ??????, ???????? ??? ????????? PostgreSQL
spring.datasource.password=1234

# ??? ????????? ???????? Hibernate ????????????? ?????????/????????? ??????? ?? ?????? ??????? (Entity).
spring.jpa.hibernate.ddl-auto=update
# ????????? ??????? ??? PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# ?????????? ??????????????? SQL-??????? ? ??????? (??????? ??? ???????)
spring.jpa.show-sql=true